[package]
name = "scout-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
rand.workspace = true
zeroize.workspace = true
hex.workspace = true
chacha20poly1305.workspace = true
argon2.workspace = true
blake3 = "1"
