[package]
name = "scout-fc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-serial.workspace = true
tracing.workspace = true
time.workspace = true
mavlink.workspace = true
